### ISSUE TITLE
Unable to build when using RP2040

### ISSUE THREAD

**Issue by redstonee** [gerivega/Arduino-IRremote#2]
Hello! Thanks a lot for this great project! However when I tried to use this with RPi Pico, it couldn't be succesfully compiled, leaving over 300 lines of errors. So is there any solution to make it work with RP2040? Appreciate!

**Comment by gerivega** [comment]
Thanks for your interest. Sorry I don't have experience with pi Pico. Only Arduino and ESP32. I can not help you with that.

**Comment by redstonee** [comment]
That's alright. I'll try some other methods😁
